name: Karrier push protobuf

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'karrier push message'
        required: true
  push:
    branches:
      - $default-branch
    paths:
      - "**.proto"

jobs:
  push:
    runs-on: [ self-hosted, linux, x64 ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Install karrier
        env:
          GO111MODULE: on
          GOPRIVATE: github.com/daangn
        run: |
          git config --global url."https://x-access-token:${{ secrets.ORG_GITHUB_READ_TOKEN }}@github.com/".insteadOf "https://github.com/"
          go install github.com/daangn/karrier/cmd/karrier@latest
      - if: ${{ github.event_name == 'push' }}
        name: Push .proto files
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_GITHUB_READ_TOKEN }}
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          karrier push -m "$(echo '${{ github.event.head_commit.message }}' | head -n 1)"
      - if: ${{ github.event_name == 'workflow_dispatch' }}
        name: Push .proto files
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_GITHUB_READ_TOKEN }}
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          karrier push -m "${{ github.event.inputs.message }}"
