name: kontrol-deploy

on:
  push:
    branches: [$default-branch]

jobs:
  deploy:
    runs-on: [self-hosted, linux, x64]

    steps:
      - uses: daangn/kontrol-deploy-action@v1
        with:
          project: ${{ github.repository }}
          token: ${{ secrets.ORG_GITHUB_READ_TOKEN }}
